services:
  mysql:
    image: mysql:8.0
    container_name: ocean-backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ocean-backend
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always

  redis-master:
    image: redis:7.0
    hostname: redis-master
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
    networks:
      - app-network
    environment:
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis-slave-1:
    image: redis:7.0
    hostname: redis-slave-1
    container_name: redis-slave-1
    ports:
      - "6479:6379"
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_REPLICATION_MODE=slave
    command: [ "redis-server", "--replicaof", "redis-master", "6379" ]
    depends_on:
      - redis-master
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "info", "replication", "|", "grep", "'role:slave'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-slave-2:
    image: redis:7.0
    hostname: redis-slave-2
    container_name: redis-slave-2
    ports:
      - "6579:6379"
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_REPLICATION_MODE=slave
    command: [ "redis-server", "--replicaof", "redis-master", "6379" ]
    depends_on:
      - redis-master
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "info", "replication", "|", "grep", "'role:slave'" ]
      interval: 10s
      timeout: 5s
      retries: 5


  sentinel-1:
    image: redis:7.0
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel:/etc/sentinel
    command: >
      redis-sentinel /etc/sentinel/sentinel.conf
    networks:
      - app-network
    depends_on:
      - redis-master
      - redis-slave-1

  sentinel-2:
    image: redis:7.0
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel:/etc/sentinel
    command: >
      redis-sentinel /etc/sentinel/sentinel.conf
    networks:
      - app-network
    depends_on:
      - redis-master
      - redis-slave-1

  sentinel-3:
    image: redis:7.0
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel:/etc/sentinel
    command: >
      redis-sentinel /etc/sentinel/sentinel.conf
    networks:
      - app-network
    depends_on:
      - redis-master
      - redis-slave-1

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    depends_on:
      - prometheus
    networks:
      - app-network

  node_exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db-data:
  grafana-data:
  prometheus-data: